steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/cloudside-academy/hariesh1', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/cloudside-academy/hariesh1"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create release-$_[A-Z0-9_]+
    --delivery-pipeline=cloud-deploy-mp1
    --region=us-central1
    --source=./
    --images=hariesh1=gcr.io/cloudside-academy/hariesh1:latest
